### ISSUE TITLE
链接期间出现 无法解析的外部符号 错误

### ISSUE THREAD

**Issue by EricSolshkov** [AngryAccelerated/Physics2D-TestBed-Qt#1]
1>render.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class QVector<class QPointF> & __cdecl QVector<class QPointF>::operator<<(class QPointF &&)" (__imp_??6?$QVector@VQPointF@@@@QEAAAEAV0@$$QEAVQPointF@@@Z)，函数 "public: static void __cdecl Physics2D::RendererQtImpl::renderPoints(class QPainter *,class Physics2D::Camera *,class std::vector<struct Physics2D::Vector2,class std::allocator<struct Physics2D::Vector2> > const &,class QPen const &)" (?renderPoints@RendererQtImpl@Physics2D@@SAXPEAVQPainter@@PEAVCamera@2@AEBV?$vector@UVector2@Physics2D@@V?$allocator@UVector2@Physics2D@@@std@@@std@@AEBVQPen@@@Z) 中引用了该符号
1>testbed.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) private: void __cdecl QRandomGenerator::_fillRange(void *,void *)" (__imp_?_fillRange@QRandomGenerator@@AEAAXPEAX0@Z)，函数 "public: void __cdecl QRandomGenerator::fillRange<unsigned int,1>(unsigned int *,__int64)" (??$fillRange@I$00@QRandomGenerator@@QEAAXPEAI_J@Z) 中引用了该符号
1>testbed.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class QRandomGenerator64 * __cdecl QRandomGenerator64::global(void)" (__imp_?global@QRandomGenerator64@@SAPEAV1@XZ)，函数 "public: static class QRandomGenerator * __cdecl QRandomGenerator::global(void)" (?global@QRandomGenerator@@SAPEAV1@XZ) 中引用了该符号
本地Qt版本为5.14.2
请问具体使用了什么版本的Qt？

**Comment by acrlw** [comment]
> 1>render.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class QVector & __cdecl QVector::operator<<(class QPointF &&)" (__imp_??6?$QVector@VQPointF@@@@QEAAAEAV0@$$QEAVQPointF@@@z)，函数 "public: static void __cdecl Physics2D::RendererQtImpl::renderPoints(class QPainter *,class Physics2D::Camera *,class std::vector<struct Physics2D::Vector2,class std::allocator > const &,class QPen const &)" (?renderPoints@RendererQtImpl@Physics2D@@SAXPEAVQPainter@@PEAVCamera@2@AEBV?$vector@UVector2@Physics2D@@v?$allocator@UVector2@Physics2D@@@std@@@std@@AEBVQPen@@@z) 中引用了该符号 1>testbed.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) private: void __cdecl QRandomGenerator::_fillRange(void *,void *)" (__imp_?_fillRange@QRandomGenerator@@AEAAXPEAX0@Z)，函数 "public: void __cdecl QRandomGenerator::fillRange<unsigned int,1>(unsigned int *,__int64)" (??$fillRange@I$00@QRandomGenerator@@QEAAXPEAI_J@Z) 中引用了该符号 1>testbed.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class QRandomGenerator64 * __cdecl QRandomGenerator64::global(void)" (__imp_?global@QRandomGenerator64@@SAPEAV1@XZ)，函数 "public: static class QRandomGenerator * __cdecl QRandomGenerator::global(void)" (?global@QRandomGenerator@@SAPEAV1@XZ) 中引用了该符号 本地Qt版本为5.14.2 请问具体使用了什么版本的Qt？

项目构建使用的 Qt 版本是 5.15.0

**Comment by EricSolshkov** [comment]
上述问题出现在Visual Studio 2019中，如果在QtCreator中通过cmake进行build则无此问题，可以正常编译运行。
